ci(skore-hub-project): Filter deprecation warnings caused by `seaborn` when using `skore>=0.11.6` (#2282)
Fixes

```python-traceback
skore/src/skore/_sklearn/_plot/metrics/precision_recall_curve.py:224: in _plot_matplotlib
    facet_grid = sns.relplot(
        col        = None
        columns_to_convert = Index(['split'], dtype='object')
        despine    = True
        hue        = None
        is_cross_validation = True
        kwargs     = {'alpha': 0.4,

[...]

seaborn/relational.py:313: in plot
    for _, unit_data in sub_data.groupby("units"):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
        _          = <bound method IdentityTransform.transform of <matplotlib.transforms.IdentityTransform object at 0x72d27d9bcc90>>
        agg        = <seaborn._statistics.EstimateAggregator object at 0x72d27e19f890>
        ax         = <Axes: >
        col        = 'ymax'
        err_kws    = {'alpha': 0.2}
        grouping_vars = ('hue', 'size', 'style')
        inv        = <bound method IdentityTransform.transform of <matplotlib.transforms.IdentityTransform object at 0x72d27d9bcc90>>
        kws        = {'alpha': 0.4,


[...]

pandas/core/frame.py:9210: in groupby
    return DataFrameGroupBy(
        DataFrameGroupBy = <class 'pandas.core.groupby.generic.DataFrameGroupBy'>
        as_index   = True
        axis       = 0
        by         = 'units'
        dropna     = True
        group_keys = True
        level      = None
        observed   = <no_default>
        self       =         x    y units  ymin  ymax

[...]

        if observed is lib.no_default:
            if any(ping._passed_categorical for ping in grouper.groupings):
>               warnings.warn(
                    "The default of observed=False is deprecated and will be changed "
                    "to True in a future version of pandas. Pass observed=False to "
                    "retain current behavior or observed=True to adopt the future "
                    "default and silence this warning.",
                    FutureWarning,
                    stacklevel=find_stack_level(),
                )
E               FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

FAILED skore-hub-project/tests/unit/artifact/media/test_performance.py::test_performance[PrecisionRecallTest[cross-validation]] - FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
```