fix(skore-hub-project/tests): Ignore `Precision is ill-defined` warning (#2307)
Fixing the flaky 🔴 CI on main.

```python-traceback
FAILED tests/unit/report/test_cross_validation_report.py::TestCrossValidationReportPayload::test_metrics_raises_exception - AssertionError: Regex pattern did not match.
  Expected regex: 'test_metrics_raises_exception'
  Actual message: 'Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.'
```