fix(tests): Remove side-effect of `test_warning_old_joblib` (#1517)
This test included a `del sys.modules` which caused issues in other
tests when run locally.

Here is a small sample of the test failures:
```
FAILED tests/unit/project/test_notes.py::TestNotes::test_put_with_note_wrong_type[in_memory_project] - AttributeError: 'module' object at skore.project has no attribute 'project'
FAILED tests/unit/test_config.py::test_config_context - AssertionError: assert {'show_progress': False} == {'show_progress': True}
FAILED tests/unit/test_config.py::test_set_config - assert False is True
FAILED tests/unit/test_config.py::test_config_context_exception - assert False is True
ERROR tests/unit/item/test_matplotlib_figure_item.py::TestMatplotlibFigureItem::test_backend_switch_in_thread - AttributeError: 'module' object at skore.persistence has no attribute 'persistence'
```

Co-authored-by: Thomas S <thomas@probabl.ai>