chore(skore-hub-project): Fix typings (#2076)
Prerequisite for https://github.com/probabl-ai/skore/pull/2069.

```bash
python -m mypy --config-file=skore-hub-project/pyproject.toml skore-hub-project/                                                                                                                                                        

skore-hub-project/src/skore_hub_project/client/api.py:129: error: "HTTPError" has no attribute "response"  [attr-defined]
skore-hub-project/src/skore_hub_project/client/client.py:61: error: Incompatible types in assignment (expression has type "tuple[type[TimeoutException], type[NetworkError], type[RemoteProtocolError]]", variable has type "tuple[HTTPError, ...]")  [assignment]
skore-hub-project/src/skore_hub_project/client/client.py:96: error: Exception type must be derived from BaseException (or be a tuple of exception classes)  [misc]
skore-hub-project/src/skore_hub_project/report/report.py:86: error: Unexpected keyword argument "report" for "Metric"  [call-arg]
skore-hub-project/src/skore_hub_project/report/report.py:108: error: Missing named argument "content_type" for "Media"  [call-arg]
skore-hub-project/src/skore_hub_project/report/report.py:108: error: Missing named argument "name" for "Media"  [call-arg]
```

---

Note that i:
- changed the way a subclass of `ReportPayload` / `Media`/`Metric` can
restrict the type of `report`: it worked at runtime but broke the static
typing (in particular the Liskov Substitution Principle - LSP),
- set abstract pydantic property in abstractclass as
`Field(init=False)`.